services:
  app:
    image: todo-front-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    ports:
      - 3000:3000
    container_name: todo-front-dev
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001