services:
  nginx:
    image: nginx:1.20.1
    container_name: phonebook-nginx-prod
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app
      - server

  app:
    image: phonebook-frontend-prod
    container_name: phonebook-frontend-prod

  server:
    image: phonebook-backend-prod
    container_name: phonebook-backend-prod
    env_file:
      - ./backend/.env